/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CommercialEditComponent: typeof import('./src/components/CommercialEditComponent.vue')['default']
    ContractorTable: typeof import('./src/components/ContractorTable.vue')['default']
    GoogleButton: typeof import('./src/components/GoogleButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LocaleSwitch: typeof import('./src/components/LocaleSwitch.vue')['default']
    NewProjectForm: typeof import('./src/components/NewProjectForm.vue')['default']
    NewProjectMemberButton: typeof import('./src/components/NewProjectMemberButton.vue')['default']
    NewPropertyButton: typeof import('./src/components/NewPropertyButton.vue')['default']
    NewRentableUnitButton: typeof import('./src/components/NewRentableUnitButton.vue')['default']
    ProjectMemberSettings: typeof import('./src/components/ProjectMemberSettings.vue')['default']
    ProjectMemberTable: typeof import('./src/components/ProjectMemberSettings.vue')['default']
    ProjectSelectionTable: typeof import('./src/components/ProjectSelectionTable.vue')['default']
    ReusableFormComponent: typeof import('./src/components/ReusableFormComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SiteFormComponent: typeof import('./src/components/SiteFormComponent.vue')['default']
    TaskTable: typeof import('./src/components/TaskTable.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
