import globals from 'globals';
import js from '@eslint/js';
import ts from 'typescript-eslint';
import vue from 'eslint-plugin-vue';
import prettier from 'eslint-plugin-prettier/recommended';

export default [
  {
    files: ['**/*.{js,jsx,cjs,mjs,ts,tsx,cts,mts,vue}'],
    languageOptions: {
      globals: {
        ...globals.browser,
        //PrimeVue Components
        Accordion: 'readonly',
        AccordionTab: 'readonly',
        AutoComplete: 'readonly',
        Avatar: 'readonly',
        AvatarGroup: 'readonly',
        Badge: 'readonly',
        BlockUI: 'readonly',
        Breadcrumb: 'readonly',
        Button: 'readonly',
        ButtonGroup: 'readonly',
        Calendar: 'readonly',
        Card: 'readonly',
        Chart: 'readonly',
        Carousel: 'readonly',
        CascadeSelect: 'readonly',
        Checkbox: 'readonly',
        Chip: 'readonly',
        Chips: 'readonly',
        ColorPicker: 'readonly',
        Column: 'readonly',
        ColumnGroup: 'readonly',
        ConfirmDialog: 'readonly',
        ConfirmPopup: 'readonly',
        ContextMenu: 'readonly',
        DataTable: 'readonly',
        DataView: 'readonly',
        DataViewLayoutOptions: 'readonly',
        DeferredContent: 'readonly',
        Dialog: 'readonly',
        Divider: 'readonly',
        Dock: 'readonly',
        Dropdown: 'readonly',
        DynamicDialog: 'readonly',
        Fieldset: 'readonly',
        FileUpload: 'readonly',
        FloatLabel: 'readonly',
        Galleria: 'readonly',
        IconField: 'readonly',
        Image: 'readonly',
        InlineMessage: 'readonly',
        Inplace: 'readonly',
        InputGroup: 'readonly',
        InputGroupAddon: 'readonly',
        InputIcon: 'readonly',
        InputMask: 'readonly',
        InputNumber: 'readonly',
        InputSwitch: 'readonly',
        InputText: 'readonly',
        Knob: 'readonly',
        Listbox: 'readonly',
        MegaMenu: 'readonly',
        Menu: 'readonly',
        Menubar: 'readonly',
        Message: 'readonly',
        MultiSelect: 'readonly',
        OrderList: 'readonly',
        OrganizationChart: 'readonly',
        OverlayPanel: 'readonly',
        Paginator: 'readonly',
        Panel: 'readonly',
        PanelMenu: 'readonly',
        Password: 'readonly',
        PickList: 'readonly',
        ProgressBar: 'readonly',
        ProgressSpinner: 'readonly',
        RadioButton: 'readonly',
        Rating: 'readonly',
        Row: 'readonly',
        SelectButton: 'readonly',
        ScrollPanel: 'readonly',
        ScrollTop: 'readonly',
        Slider: 'readonly',
        Sidebar: 'readonly',
        Skeleton: 'readonly',
        SpeedDial: 'readonly',
        SplitButton: 'readonly',
        Splitter: 'readonly',
        SplitterPanel: 'readonly',
        Steps: 'readonly',
        TabMenu: 'readonly',
        TabView: 'readonly',
        TabPanel: 'readonly',
        Tag: 'readonly',
        Textarea: 'readonly',
        Terminal: 'readonly',
        TieredMenu: 'readonly',
        Timeline: 'readonly',
        Toast: 'readonly',
        Toolbar: 'readonly',
        ToggleButton: 'readonly',
        Tree: 'readonly',
        TreeSelect: 'readonly',
        TreeTable: 'readonly',
        TriStateCheckbox: 'readonly',
        VirtualScroller: 'readonly',
      },
    },
  },

  // js
  js.configs.recommended,
  {
    rules: {
      'no-unused-vars': 'off',
      'no-undef': 'off',
    },
  },

  // ts
  ...ts.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },

  // vue
  ...vue.configs['flat/recommended'],
  {
    // files: ['*.vue', '**/*.vue'],
    languageOptions: {
      parserOptions: {
        parser: ts.parser,
      },
    },
  },
  {
    rules: {
      'vue/multi-word-component-names': 'off',
      'vue/attribute-hyphenation': ['error', 'never'],
      'vue/v-on-event-hyphenation': ['error', 'never'],
      'vue/no-v-html': 'off',
      'vue/block-lang': ['error', { script: { lang: 'ts' } }],
      'vue/block-order': ['error', { order: ['script[setup]', 'template', 'style[scoped]'] }],
      'vue/component-api-style': ['error', ['script-setup']],
      'vue/component-name-in-template-casing': 'error',
      'vue/custom-event-name-casing': 'error',
      'vue/define-emits-declaration': 'error',
      'vue/define-macros-order': [
        'error',
        {
          order: ['defineOptions', 'defineModel', 'defineProps', 'defineEmits', 'defineSlots'],
          defineExposeLast: true,
        },
      ],
      'vue/define-props-declaration': 'error',
      'vue/html-button-has-type': 'warn',
      'vue/no-multiple-objects-in-class': 'warn',
      'vue/no-root-v-if': 'error',
      'vue/no-template-target-blank': 'error',
      'vue/no-undef-components': 'error',
      'vue/no-undef-properties': 'error',
      'vue/no-unused-refs': 'warn',
      'vue/no-use-v-else-with-v-for': 'error',
      'vue/no-useless-mustaches': 'warn',
      'vue/no-useless-v-bind': 'warn',
      'vue/no-v-text': 'error',
      'vue/padding-line-between-blocks': 'warn',
      'vue/prefer-define-options': 'error',
      'vue/prefer-separate-static-class': 'warn',
      'vue/prefer-true-attribute-shorthand': 'warn',
      'vue/require-macro-variable-name': 'error',
      'vue/require-typed-ref': 'warn',
      'vue/v-for-delimiter-style': 'error',
      'vue/valid-define-options': 'error',
    },
  },

  // prettier
  prettier,
  {
    rules: {
      'prettier/prettier': 'warn',
    },
  },

  // ignore files at the end of the config
  {
    ignores: ['**/dist/**', 'node_modules/*', 'cypress/**', 'html/**', 'coverage/'],
  },
];
