/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/notification/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Send Test Emails */
        get: {
            parameters: {
                query: {
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The address of a customer, a building or a site */
        AddressJson: {
            street?: string;
            city?: string;
            province?: string;
            zip?: string;
            countryCode?: string;
        };
        AddressModel: {
            street?: string;
            city?: string;
            province?: string;
            zip?: string;
            country?: components["schemas"]["Locale"];
        };
        /** @description An apartment inside a building according to WoFIV */
        ApartmentJson: {
            type?: components["schemas"]["UnitType"];
            /** Format: float */
            livingSpace?: number;
            /** Format: float */
            usableSpace?: number;
            /** Format: float */
            heatingSpace?: number;
            /** Format: float */
            space?: number;
            location?: string;
            description?: string;
            id?: string;
            title?: string;
        };
        /** @enum {string} */
        BillingCycle: "WEEKLY" | "MONTHLY";
        /** @description A building as part of a property */
        BuildingJson: {
            type?: components["schemas"]["UnitType"];
            /** Format: float */
            grossFloorArea?: number;
            /** Format: float */
            netFloorArea?: number;
            /** Format: float */
            constructionFloorArea?: number;
            /** Format: float */
            livingSpace?: number;
            /** Format: float */
            usableSpace?: number;
            /** Format: float */
            heatingSpace?: number;
            /** Format: float */
            space?: number;
            location?: string;
            description?: string;
            id?: string;
            title?: string;
            address?: components["schemas"]["AddressModel"];
        };
        /** @description A single chat message */
        ChatMessageJson: {
            messageId?: components["schemas"]["UUID"];
            chatSessionId?: components["schemas"]["UUID"];
            senderId?: components["schemas"]["UUID"];
            contentType?: string;
            content?: string;
            url?: string;
            createdAt?: components["schemas"]["Instant"];
        };
        /** @description A list of chat messages */
        ChatMessageListJson: {
            messages?: components["schemas"]["ChatMessageJson"][];
        };
        /** @description A chat session */
        ChatSessionJson: {
            sessionId?: components["schemas"]["UUID"];
            projectId?: components["schemas"]["UUID"];
            taskId?: components["schemas"]["UUID"];
            createdAt?: components["schemas"]["Instant"];
            modifiedAt?: components["schemas"]["Instant"];
        };
        /** @description An commercial inside a building */
        CommercialJson: {
            type?: components["schemas"]["UnitType"];
            /** Format: float */
            netFloorArea?: number;
            /** Format: float */
            usableFloorArea?: number;
            /** Format: float */
            technicalServicesArea?: number;
            /** Format: float */
            trafficArea?: number;
            /** Format: float */
            heatingSpace?: number;
            /** Format: float */
            space?: number;
            location?: string;
            description?: string;
            id?: string;
            title?: string;
        };
        /** @description A country item of a list */
        CountryItemJson: {
            countryCode: string;
            name: string;
        };
        /** @description A list of countries */
        CountryListJson: {
            countries?: components["schemas"]["CountryItemJson"][];
        };
        /** Format: date-time */
        Instant: string;
        /** Format: date */
        LocalDate: string;
        /** Format: date-time */
        LocalDateTime: string;
        Locale: {
            language?: string;
            script?: string;
            country?: string;
            variant?: string;
            extensionKeys?: string[];
            unicodeLocaleAttributes?: string[];
            unicodeLocaleKeys?: string[];
            iSO3Language?: string;
            iSO3Country?: string;
            displayLanguage?: string;
            displayScript?: string;
            displayCountry?: string;
            displayVariant?: string;
            displayName?: string;
        };
        /** @enum {string} */
        MemberRole: "PROPRIETOR" | "MANAGER" | "LESSOR" | "STAFF" | "COLLABORATOR";
        /** @description A project item with the user's member role only */
        ProjectItemJson: {
            id: string;
            name: string;
            memberRole: components["schemas"]["MemberRole"];
        };
        /** @description A project */
        ProjectJson: {
            id?: string;
            title: string;
            members?: components["schemas"]["ProjectMemberJson"][];
        };
        /** @description A list of projects */
        ProjectListJson: {
            /**
             * Format: int32
             * @description Index of the first element in projects list of total available entries, starting at 1
             */
            first: number;
            /**
             * Format: int32
             * @description Number of elements in projects list
             * @default 10
             */
            size: number;
            /**
             * Format: int64
             * @description Total number of available projects
             */
            total: number;
            projects?: components["schemas"]["ProjectItemJson"][];
        };
        /** @description Project member information in context of a project */
        ProjectMemberJson: {
            privileged?: boolean;
            id?: string;
            name?: string;
            email?: string;
            active?: boolean;
            role: components["schemas"]["MemberRole"];
        };
        /** @description A list of project members */
        ProjectMemberListJson: {
            members: components["schemas"]["ProjectMemberJson"][];
        };
        /** @description A property */
        PropertyJson: {
            type?: components["schemas"]["UnitType"];
            landRegistry?: string;
            cadastralDistrict?: string;
            sheetNumber?: string;
            /** Format: int32 */
            plotNumber?: number;
            cadastralSection?: string;
            plot?: string;
            economyType?: string;
            location?: string;
            /** Format: int32 */
            plotArea?: number;
            /** Format: float */
            space?: number;
            description?: string;
            id?: string;
            title?: string;
        };
        /** @description A list of properties */
        PropertyListJson: {
            properties?: components["schemas"]["RentalUnitTreeNodeJson"][];
        };
        /** @description A rent of a tenancy */
        RentJson: {
            billingCycle: components["schemas"]["BillingCycle"];
            firstPaymentDate: components["schemas"]["LocalDate"];
            lastPaymentDate?: components["schemas"]["LocalDate"];
            /** Format: float */
            basicRent?: number;
            /** Format: float */
            operatingCostsPrepayment?: number;
            /** Format: float */
            heatingCostsPrepayment?: number;
        };
        /** @description Encapsulated data of a project tree node */
        RentalUnitNodeDataJson: {
            id?: string;
            /** @description Type of the node (e.g., 'PROPERTY', 'BUILDING') */
            type: components["schemas"]["UnitType"];
            /** @description Title of the node */
            title?: string;
            /** @description Location of the rental unit */
            location?: string;
            /** @description Description of the rental unit */
            description?: string;
            /** @description Name of the tenant associated with this node */
            tenant?: string;
            /**
             * Format: float
             * @description Usable space in square meters
             */
            space?: number;
        };
        /** @description A tree node representing a project entity */
        RentalUnitTreeNodeJson: {
            /** @description Key of the node */
            key: string;
            /** @description Data encapsulating node attributes */
            data?: components["schemas"]["RentalUnitNodeDataJson"];
            /** @description Children nodes */
            children?: components["schemas"]["RentalUnitTreeNodeJson"][];
        };
        /** @description A site as part of a property */
        SiteJson: {
            type?: components["schemas"]["UnitType"];
            /** Format: float */
            outdoorArea?: number;
            /** Format: float */
            space?: number;
            location?: string;
            description?: string;
            id?: string;
            title?: string;
            address?: components["schemas"]["AddressJson"];
        };
        /** @enum {string} */
        Status: "PENDING" | "OPEN" | "IN_PROGRESS" | "CLOSED" | "REJECTED";
        /** @description A storage inside a building but with living space according to WoFIV */
        StorageJson: {
            type?: components["schemas"]["UnitType"];
            /** Format: float */
            usableSpace?: number;
            /** Format: float */
            heatingSpace?: number;
            /** Format: float */
            space?: number;
            location?: string;
            description?: string;
            id?: string;
            title?: string;
        };
        /** @description A task item with basic information */
        TaskItemJson: {
            id?: string;
            name?: string;
            title?: string;
            type?: components["schemas"]["Type"];
            status?: components["schemas"]["Status"];
            owner?: string;
        };
        /** @description A task */
        TaskJson: {
            reporterId?: string;
            id?: string;
            projectId?: string;
            title?: string;
            type?: components["schemas"]["Type"];
            status?: components["schemas"]["Status"];
            ownerId?: string;
            description?: string;
            blockedBy?: string;
            relatedTo?: string;
            duplicateOf?: string;
        };
        /** @description A list of tasks */
        TaskListJson: {
            tasks?: components["schemas"]["TaskItemJson"][];
        };
        /** @description A tenancy item with basic information from a tenant's perspective */
        TenancyItemJson: {
            id?: string;
            name?: string;
            /** @description Type of the node (e.g., 'PROPERTY', 'BUILDING') */
            rentalType: components["schemas"]["UnitType"];
            /** @description Title of the node */
            rentalTitle?: string;
            active?: boolean;
        };
        /** @description A tenancy of a rentable unit */
        TenancyJson: {
            active?: boolean;
            id?: string;
            tenants?: components["schemas"]["UserJson"][];
            startOfRental?: components["schemas"]["LocalDate"];
            endOfRental?: components["schemas"]["LocalDate"];
        };
        /** @description A read-only tenancy of a rentable unit from a tenant's perspective */
        TenancyJson1: {
            id?: string;
            /** @description Type of the node (e.g., 'PROPERTY', 'BUILDING') */
            rentalType: components["schemas"]["UnitType"];
            /** @description Title of the node */
            rentalTitle?: string;
            startOfRental?: components["schemas"]["LocalDate"];
            endOfRental?: components["schemas"]["LocalDate"];
            billingCycle?: components["schemas"]["BillingCycle"];
            /** Format: float */
            basicRent?: number;
            /** Format: float */
            operatingCostsPrepayment?: number;
            /** Format: float */
            heatingCostsPrepayment?: number;
        };
        /** @description A list of tenancies from a tenant's perspective */
        TenancyListJson: {
            tenancies?: components["schemas"]["TenancyItemJson"][];
        };
        /** @enum {string} */
        Type: "TASK" | "DEFECT" | "MAINTENANCE";
        /** Format: uuid */
        UUID: string;
        /** @enum {string} */
        UnitType: "PROPERTY" | "SITE" | "BUILDING" | "APARTMENT" | "STORAGE" | "COMMERCIAL";
        /** @description User information globally */
        UserJson: {
            active?: boolean;
            id?: string;
            userRoles?: components["schemas"]["UserRole"][];
            email?: string;
            firstName?: string;
            lastName?: string;
            address?: components["schemas"]["AddressJson"];
            mobilePhoneNumber?: string;
            businessPhoneNumber?: string;
            privatePhoneNumber?: string;
            registeredDate?: components["schemas"]["LocalDate"];
            lastLoginDate?: components["schemas"]["LocalDateTime"];
        };
        /** @enum {string} */
        UserRole: "MANAGER" | "TENANT" | "CONTRACTOR";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
