/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'LandingPage': RouteRecordInfo<
      'LandingPage',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ContractorClientsClosed': RouteRecordInfo<
      'ContractorClientsClosed',
      '/contractor/clients/closed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ContractorClientsOngoing': RouteRecordInfo<
      'ContractorClientsOngoing',
      '/contractor/clients/ongoing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ContractorClientsOpen': RouteRecordInfo<
      'ContractorClientsOpen',
      '/contractor/clients/open',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ContractorDashboard': RouteRecordInfo<
      'ContractorDashboard',
      '/contractor/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ContractorView': RouteRecordInfo<
      'ContractorView',
      '/contractor/issues',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Inbox': RouteRecordInfo<
      'Inbox',
      '/inbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'InboxDetail': RouteRecordInfo<
      'InboxDetail',
      '/inbox/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'LegalNotice': RouteRecordInfo<
      'LegalNotice',
      '/legal-notice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ManagerAccountSettings': RouteRecordInfo<
      'ManagerAccountSettings',
      '/manager/account-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ManagerDashboard': RouteRecordInfo<
      'ManagerDashboard',
      '/manager/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ManagerOrganizations': RouteRecordInfo<
      'ManagerOrganizations',
      '/manager/organizations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ProjectSelection': RouteRecordInfo<
      'ProjectSelection',
      '/manager/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ManagerSettings': RouteRecordInfo<
      'ManagerSettings',
      '/manager/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Privacy': RouteRecordInfo<
      'Privacy',
      '/privacy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'RentalAgreementView': RouteRecordInfo<
      'RentalAgreementView',
      '/projects/:projectId/agreements',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    'RentalAgreementDetails': RouteRecordInfo<
      'RentalAgreementDetails',
      '/projects/:projectId/agreements/:agreementId',
      { projectId: ParamValue<true>, agreementId: ParamValue<true> },
      { projectId: ParamValue<false>, agreementId: ParamValue<false> },
      | never
    >,
    'ProjectChatView': RouteRecordInfo<
      'ProjectChatView',
      '/projects/:projectId/chat',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    'ProjectContractorList': RouteRecordInfo<
      'ProjectContractorList',
      '/projects/:projectId/contractors',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    'ProjectDashboard': RouteRecordInfo<
      'ProjectDashboard',
      '/projects/:projectId/dashboard',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    'IssueOverview': RouteRecordInfo<
      'IssueOverview',
      '/projects/:projectId/issues',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    'IssueDetails': RouteRecordInfo<
      'IssueDetails',
      '/projects/:projectId/issues/:issueId',
      { projectId: ParamValue<true>, issueId: ParamValue<true> },
      { projectId: ParamValue<false>, issueId: ParamValue<false> },
      | never
    >,
    'ProjectSettings': RouteRecordInfo<
      'ProjectSettings',
      '/projects/:projectId/settings',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    'TenantList': RouteRecordInfo<
      'TenantList',
      '/projects/:projectId/tenants',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    'TenantDetail': RouteRecordInfo<
      'TenantDetail',
      '/projects/:projectId/tenants/:tenantId',
      { projectId: ParamValue<true>, tenantId: ParamValue<true> },
      { projectId: ParamValue<false>, tenantId: ParamValue<false> },
      | never
    >,
    'RentableUnits': RouteRecordInfo<
      'RentableUnits',
      '/projects/:projectId/units',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    'ApartmentView': RouteRecordInfo<
      'ApartmentView',
      '/projects/:projectId/units/apartment/:unitId',
      { projectId: ParamValue<true>, unitId: ParamValue<true> },
      { projectId: ParamValue<false>, unitId: ParamValue<false> },
      | never
    >,
    'BuildingView': RouteRecordInfo<
      'BuildingView',
      '/projects/:projectId/units/building/:unitId',
      { projectId: ParamValue<true>, unitId: ParamValue<true> },
      { projectId: ParamValue<false>, unitId: ParamValue<false> },
      | never
    >,
    'CommercialView': RouteRecordInfo<
      'CommercialView',
      '/projects/:projectId/units/commercial/:unitId',
      { projectId: ParamValue<true>, unitId: ParamValue<true> },
      { projectId: ParamValue<false>, unitId: ParamValue<false> },
      | never
    >,
    'PropertyView': RouteRecordInfo<
      'PropertyView',
      '/projects/:projectId/units/property/:unitId',
      { projectId: ParamValue<true>, unitId: ParamValue<true> },
      { projectId: ParamValue<false>, unitId: ParamValue<false> },
      | never
    >,
    'SiteView': RouteRecordInfo<
      'SiteView',
      '/projects/:projectId/units/site/:unitId',
      { projectId: ParamValue<true>, unitId: ParamValue<true> },
      { projectId: ParamValue<false>, unitId: ParamValue<false> },
      | never
    >,
    'StorageView': RouteRecordInfo<
      'StorageView',
      '/projects/:projectId/units/storage/:unitId',
      { projectId: ParamValue<true>, unitId: ParamValue<true> },
      { projectId: ParamValue<false>, unitId: ParamValue<false> },
      | never
    >,
    'TenantAccountSettings': RouteRecordInfo<
      'TenantAccountSettings',
      '/tenancies/account-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'TenantDashboard': RouteRecordInfo<
      'TenantDashboard',
      '/tenancies/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'TenantIssues': RouteRecordInfo<
      'TenantIssues',
      '/tenancies/issues',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'LandingPage'
      views:
        | never
    }
    'src/pages/contractor/clients/closed.vue': {
      routes:
        | 'ContractorClientsClosed'
      views:
        | never
    }
    'src/pages/contractor/clients/ongoing.vue': {
      routes:
        | 'ContractorClientsOngoing'
      views:
        | never
    }
    'src/pages/contractor/clients/open.vue': {
      routes:
        | 'ContractorClientsOpen'
      views:
        | never
    }
    'src/pages/contractor/dashboard.vue': {
      routes:
        | 'ContractorDashboard'
      views:
        | never
    }
    'src/pages/contractor/issues.vue': {
      routes:
        | 'ContractorView'
      views:
        | never
    }
    'src/pages/inbox/index.vue': {
      routes:
        | 'Inbox'
      views:
        | never
    }
    'src/pages/inbox/[id].vue': {
      routes:
        | 'InboxDetail'
      views:
        | never
    }
    'src/pages/legal-notice.vue': {
      routes:
        | 'LegalNotice'
      views:
        | never
    }
    'src/pages/manager/account-settings.vue': {
      routes:
        | 'ManagerAccountSettings'
      views:
        | never
    }
    'src/pages/manager/dashboard.vue': {
      routes:
        | 'ManagerDashboard'
      views:
        | never
    }
    'src/pages/manager/organizations.vue': {
      routes:
        | 'ManagerOrganizations'
      views:
        | never
    }
    'src/pages/manager/projects.vue': {
      routes:
        | 'ProjectSelection'
      views:
        | never
    }
    'src/pages/manager/settings.vue': {
      routes:
        | 'ManagerSettings'
      views:
        | never
    }
    'src/pages/privacy.vue': {
      routes:
        | 'Privacy'
      views:
        | never
    }
    'src/pages/projects/[projectId]/agreements/index.vue': {
      routes:
        | 'RentalAgreementView'
      views:
        | never
    }
    'src/pages/projects/[projectId]/agreements/[agreementId].vue': {
      routes:
        | 'RentalAgreementDetails'
      views:
        | never
    }
    'src/pages/projects/[projectId]/chat.vue': {
      routes:
        | 'ProjectChatView'
      views:
        | never
    }
    'src/pages/projects/[projectId]/contractors/index.vue': {
      routes:
        | 'ProjectContractorList'
      views:
        | never
    }
    'src/pages/projects/[projectId]/dashboard.vue': {
      routes:
        | 'ProjectDashboard'
      views:
        | never
    }
    'src/pages/projects/[projectId]/issues/index.vue': {
      routes:
        | 'IssueOverview'
      views:
        | never
    }
    'src/pages/projects/[projectId]/issues/[issueId].vue': {
      routes:
        | 'IssueDetails'
      views:
        | never
    }
    'src/pages/projects/[projectId]/settings.vue': {
      routes:
        | 'ProjectSettings'
      views:
        | never
    }
    'src/pages/projects/[projectId]/tenants/index.vue': {
      routes:
        | 'TenantList'
      views:
        | never
    }
    'src/pages/projects/[projectId]/tenants/[tenantId].vue': {
      routes:
        | 'TenantDetail'
      views:
        | never
    }
    'src/pages/projects/[projectId]/units/index.vue': {
      routes:
        | 'RentableUnits'
      views:
        | never
    }
    'src/pages/projects/[projectId]/units/apartment/[unitId].vue': {
      routes:
        | 'ApartmentView'
      views:
        | never
    }
    'src/pages/projects/[projectId]/units/building/[unitId].vue': {
      routes:
        | 'BuildingView'
      views:
        | never
    }
    'src/pages/projects/[projectId]/units/commercial/[unitId].vue': {
      routes:
        | 'CommercialView'
      views:
        | never
    }
    'src/pages/projects/[projectId]/units/property/[unitId].vue': {
      routes:
        | 'PropertyView'
      views:
        | never
    }
    'src/pages/projects/[projectId]/units/site/[unitId].vue': {
      routes:
        | 'SiteView'
      views:
        | never
    }
    'src/pages/projects/[projectId]/units/storage/[unitId].vue': {
      routes:
        | 'StorageView'
      views:
        | never
    }
    'src/pages/tenancies/account-settings.vue': {
      routes:
        | 'TenantAccountSettings'
      views:
        | never
    }
    'src/pages/tenancies/dashboard.vue': {
      routes:
        | 'TenantDashboard'
      views:
        | never
    }
    'src/pages/tenancies/issues/index.vue': {
      routes:
        | 'TenantIssues'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
